spring:
  profiles:
    active:
    - dev #当前使用的环境
---
content: dev content 
spring:
  profiles: dev
  application:
    naem: hello-service
---
content: test content 
spring:
  profiles: test
  application:
    naem: hello-service
  
